### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by StephanBruh** [MrBrax/TwitchAutomator#11]
I wanted to install TwitchAutomator followed all the steps without any errors, tried going to the site, and got a error 500. Checked the permissions those are all 777, got this error

```
2020/12/09 11:31:21 [error] 15338#15338: *13 FastCGI sent in stderr: "PHP message: Saving config failed, permissions issue?PHP message: PHP Warning:  file_put_contents(/var/www/TwitchAutomator/src/../l$
Stack trace:
#0 /var/www/TwitchAutomator/src/TwitchConfig.php(249): App\TwitchConfig::loadConfig()
#1 /var/www/TwitchAutomator/vendor/composer/ClassLoader.php(444): include('/var/www/Twitch...')
#2 /var/www/TwitchAutomator/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/TwitchAutomator/src/TwitchHelper.php(961): spl_autoload_call()
#5 /var/www/TwitchAutomator/vendor/composer/ClassLoader.php(444): include('/var/www/Twitch...')
#6 /var/www/TwitchAutomator/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#7 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#8 /var/www/TwitchAutomator/public/index.php(32): spl_auto
```

And this is my nginx config:

```
     root /var/www/TwitchAutomator/public;

     location / {
        try_files $uri /index.php?$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        fastcgi_index index.php;
        include fastcgi.conf;
    }
```

Somebody any ideas how to fix it?

**Comment by StephanBruh** [comment]
Fixed with:` chown -Rf www-data.www-data /var/www/TwitchAutomator/*`

**Comment by MrBrax** [comment]
Permissions are always fun!
