### ISSUE TITLE
Error: TwitchVOD.saveVTTChapters: chapters are not set

### ISSUE THREAD

**Issue by djdembeck** [MrBrax/TwitchAutomator#127]
The TwitchAutomator Docker stopped upon reaching this error. Perhaps it should be logged and not thrown, or allow the service to restart.

```
No clients connected to broker for data: {"server":true,"action":"job_clear","data":{"job_name":"capture_...
2022-04-25 16:17:56.798 | job <SUCCESS> Job capture_paymoneywubby_2022-04-25T20_53_59Z_39684127113 removed from jobs list
No clients connected to broker for data: {"server":true,"action":"end_capture","data":{"vod":{"basename":...
2022-04-25 16:17:56.828 | automator <INFO> Add end timestamp for paymoneywubby_2022-04-25T20_53_59Z_39684127113
2022-04-25 16:17:56.828 | vodclass <WARNING> Saving JSON of paymoneywubby_2022-04-25T20_53_59Z_39684127113 with no chapters!!
2022-04-25 16:17:56.829 | vodclass <SUCCESS> Saving JSON of paymoneywubby_2022-04-25T20_53_59Z_39684127113  (stream capture end)
Stopped watching paymoneywubby_2022-04-25T20_53_59Z_39684127113
Watching paymoneywubby_2022-04-25T20_53_59Z_39684127113
Sleeping for 60000ms
2022-04-25 16:17:56.831 | vodclass <INFO> VOD JSON paymoneywubby_2022-04-25T20_53_59Z_39684127113 changed (external/change)!
2022-04-25 16:17:56.831 | vodclass <INFO> VOD JSON paymoneywubby_2022-04-25T20_53_59Z_39684127113 exists (again?) change
2022-04-25 16:17:56.831 | vodclass <INFO> VOD JSON paymoneywubby_2022-04-25T20_53_59Z_39684127113 changed (external/change)!
2022-04-25 16:17:56.832 | vodclass <INFO> VOD JSON paymoneywubby_2022-04-25T20_53_59Z_39684127113 exists (again?) change
Broadcasting job update for capture_paymoneywubby_2022-04-25T20_53_59Z_39684127113
No clients connected to broker for data: {"server":true,"action":"job_clear","data":{"job_name":"capture_...
No clients connected to broker for data: {"server":true,"action":"vod_updated","data":{"vod":{"basename":...
2022-04-25 16:18:56.870 | vodclass <WARNING> Saving JSON of paymoneywubby_2022-04-25T20_53_59Z_39684127113 with no chapters!!
2022-04-25 16:18:56.871 | vodclass <SUCCESS> Saving JSON of paymoneywubby_2022-04-25T20_53_59Z_39684127113  (is_converting set)
Stopped watching paymoneywubby_2022-04-25T20_53_59Z_39684127113
Watching paymoneywubby_2022-04-25T20_53_59Z_39684127113
No clients connected to broker for data: {"server":true,"action":"start_convert","data":{"vod":{"basename...
2022-04-25 16:18:56.876 | helper <INFO> Remuxing /usr/local/share/twitchautomator/data/storage/vods/paymoneywubby_2022-04-25T20_53_59Z_39684127113.ts to /usr/local/share/twitchautomator/data/storage/vods/paymoneywubby_2022-04-25T20_53_59Z_39684127113.mp4
2022-04-25 16:18:56.883 | helper <INFO> Executing /usr/bin/ffmpeg -i /usr/local/share/twitchautomator/data/storage/vods/paymoneywubby_2022-04-25T20_53_59Z_39684127113.ts -c copy -bsf:a aac_adtstoasc -movflags faststart /usr/local/share/twitchautomator/data/storage/vods/paymoneywubby_2022-04-25T20_53_59Z_39684127113.mp4
2022-04-25 16:18:56.883 | helper <SUCCESS> Spawned process 60 for remux_paymoneywubby_2022-04-25T20_53_59Z_39684127113.ts
2022-04-25 16:18:56.884 | job <INFO> Save job remux_paymoneywubby_2022-04-25T20_53_59Z_39684127113.ts with PID 60 to /usr/local/share/twitchautomator/data/cache/pids/remux_paymoneywubby_2022-04-25T20_53_59Z_39684127113.ts.json
No clients connected to broker for data: {"server":true,"action":"job_save","data":{"job_name":"remux_pay...
2022-04-25 16:18:56.884 | helper <INFO> Attached to all streams for process 60 for remux_paymoneywubby_2022-04-25T20_53_59Z_39684127113.ts
2022-04-25 16:18:56.885 | vodclass <INFO> VOD JSON paymoneywubby_2022-04-25T20_53_59Z_39684127113 changed (external/change)!
2022-04-25 16:18:56.886 | vodclass <INFO> VOD JSON paymoneywubby_2022-04-25T20_53_59Z_39684127113 exists (again?) change
2022-04-25 16:18:56.886 | vodclass <INFO> VOD JSON paymoneywubby_2022-04-25T20_53_59Z_39684127113 changed (external/change)!
2022-04-25 16:18:56.887 | vodclass <INFO> VOD JSON paymoneywubby_2022-04-25T20_53_59Z_39684127113 exists (again?) change
Broadcasting job update for remux_paymoneywubby_2022-04-25T20_53_59Z_39684127113.ts
No clients connected to broker for data: {"server":true,"action":"job_update","data":{"job_name":"remux_p...
No clients connected to broker for data: {"server":true,"action":"vod_updated","data":{"vod":{"basename":...
2022-04-25 16:19:04.440 | helper <INFO> Process 60 for remux_paymoneywubby_2022-04-25T20_53_59Z_39684127113.ts exited with code 0
2022-04-25 16:19:04.441 | job <INFO> Clear job remux_paymoneywubby_2022-04-25T20_53_59Z_39684127113.ts with PID 60
No clients connected to broker for data: {"server":true,"action":"job_clear","data":{"job_name":"remux_pa...
2022-04-25 16:19:04.441 | job <SUCCESS> Job remux_paymoneywubby_2022-04-25T20_53_59Z_39684127113.ts removed from jobs list
2022-04-25 16:19:04.442 | job <WARNING> Job remux_paymoneywubby_2022-04-25T20_53_59Z_39684127113.ts not found in jobs list
2022-04-25 16:19:04.444 | helper <SUCCESS> Remuxed /usr/local/share/twitchautomator/data/storage/vods/paymoneywubby_2022-04-25T20_53_59Z_39684127113.ts to /usr/local/share/twitchautomator/data/storage/vods/paymoneywubby_2022-04-25T20_53_59Z_39684127113.mp4
2022-04-25 16:19:04.444 | automator <SUCCESS> Converted video /usr/local/share/twitchautomator/data/storage/vods/paymoneywubby_2022-04-25T20_53_59Z_39684127113.ts to /usr/local/share/twitchautomator/data/storage/vods/paymoneywubby_2022-04-25T20_53_59Z_39684127113.mp4
No clients connected to broker for data: {"server":true,"action":"end_convert","data":{"vod":{"basename":...
Sleeping for 10000ms
Broadcasting job update for remux_paymoneywubby_2022-04-25T20_53_59Z_39684127113.ts
No clients connected to broker for data: {"server":true,"action":"job_clear","data":{"job_name":"remux_pa...
No clients connected to broker for data: {"server":true,"action":"end_convert","data":{"vod":{"basename":...
2022-04-25 16:19:14.498 | automator <INFO> Conversion done, add segments to paymoneywubby_2022-04-25T20_53_59Z_39684127113
2022-04-25 16:19:14.498 | vodclass <INFO> Adding segment paymoneywubby_2022-04-25T20_53_59Z_39684127113.mp4 to paymoneywubby_2022-04-25T20_53_59Z_39684127113
2022-04-25 16:19:14.505 | vodclass <WARNING> Saving JSON of paymoneywubby_2022-04-25T20_53_59Z_39684127113 with no chapters!!
2022-04-25 16:19:14.508 | vodclass <SUCCESS> Saving JSON of paymoneywubby_2022-04-25T20_53_59Z_39684127113  (add segment)
Stopped watching paymoneywubby_2022-04-25T20_53_59Z_39684127113
Watching paymoneywubby_2022-04-25T20_53_59Z_39684127113
2022-04-25 16:19:14.513 | automator <INFO> Sleep 2 minutes for paymoneywubby_2022-04-25T20_53_59Z_39684127113
Sleeping for 120000ms
2022-04-25 16:19:14.513 | vodclass <INFO> VOD JSON paymoneywubby_2022-04-25T20_53_59Z_39684127113 changed (external/change)!
2022-04-25 16:19:14.514 | vodclass <INFO> VOD JSON paymoneywubby_2022-04-25T20_53_59Z_39684127113 exists (again?) change
2022-04-25 16:19:14.514 | vodclass <INFO> VOD JSON paymoneywubby_2022-04-25T20_53_59Z_39684127113 changed (external/change)!
2022-04-25 16:19:14.514 | vodclass <INFO> VOD JSON paymoneywubby_2022-04-25T20_53_59Z_39684127113 exists (again?) change
No clients connected to broker for data: {"server":true,"action":"vod_updated","data":{"vod":{"basename":...
🎥 2022-04-25T21:19:17.578Z paymoneywubby_2022-04-25T21_14_34Z_39684166409 1080p60 148.71 MB / 4780 kbps
2022-04-25 16:21:14.613 | automator <INFO> Do metadata on paymoneywubby_2022-04-25T20_53_59Z_39684127113
2022-04-25 16:21:14.614 | vodclass <INFO> Finalize paymoneywubby_2022-04-25T20_53_59Z_39684127113 @ /usr/local/share/twitchautomator/data/storage/vods
2022-04-25 16:21:14.702 | vodclass <INFO> Fetching mediainfo of paymoneywubby_2022-04-25T20_53_59Z_39684127113, segment #0
2022-04-25 16:21:14.702 | mediainfo <INFO> Run mediainfo on /usr/local/share/twitchautomator/data/storage/vods/paymoneywubby_2022-04-25T20_53_59Z_39684127113.mp4
2022-04-25 16:21:14.723 | exec <INFO> Executing mediainfo: /usr/bin/mediainfo --Full --Output=JSON /usr/local/share/twitchautomator/data/storage/vods/paymoneywubby_2022-04-25T20_53_59Z_39684127113.mp4
2022-04-25 16:21:14.875 | helper <INFO> Process 61 for mediainfo exited with code 0
/usr/local/share/twitchautomator/server/src/Core/TwitchVOD.ts:1191
            throw new Error("TwitchVOD.saveVTTChapters: chapters are not set");
                  ^

Error: TwitchVOD.saveVTTChapters: chapters are not set
    at _TwitchVOD.saveVTTChapters (/usr/local/share/twitchautomator/server/src/Core/TwitchVOD.ts:1191:19)
    at _TwitchVOD.finalize (/usr/local/share/twitchautomator/server/src/Core/TwitchVOD.ts:1012:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Automator.download (/usr/local/share/twitchautomator/server/src/Core/Automator.ts:719:9)
    at Automator.handle (/usr/local/share/twitchautomator/server/src/Core/Automator.ts:189:13)

Node.js v17.9.0
error Command failed with exit code 1.
```

**Comment by MrBrax** [comment]
did the stream not get any chapters at all?

**Comment by djdembeck** [comment]
The streamer's internet was cutting out, so the stream in question lasted ~6 minutes. I'm guessing this caused no chapters.

**Comment by MrBrax** [comment]
gotcha
