### ISSUE TITLE
crash when recording because "uid"

### ISSUE THREAD

**Issue by mr-flibble** [MrBrax/TwitchAutomator#169]
Hello, I just started testing new version and set up couple recording to test it. In the morning i noticed that docker container crashed  with error:
`TypeError [ERR_INVALID_ARG_TYPE]: The "uid" argument must be of type number. Received type string ('nobody')`
(fulllog below). 
I figured it was permission problem, so I changed permissions from 775 to 777 but it crashed same.
Interestingly, json file in vod folder is created with permissions 0644, and ownership "root [0]" but then it crashed

**I tried:**
set chown in advanced settings to root, but it crashed:
`TypeError [ERR_INVALID_ARG_TYPE]: The "uid" argument must be of type number. Received type string ('root')`
set chown in advanced settings zero, but it crashed:
`TypeError [ERR_INVALID_ARG_TYPE]: The "uid" argument must be of type number. Received type string ('0')`
uncheck "Set file permissions" in advanced settings - but **the settings are not saved** (should i create separate issue for that?)

**What's working**
- download clip
- download vod
- download chat

**What's don't work**
- recording when channel come alive
- "Force record" channel that is online 

**My environment:**
latest docker-compose version on Ubuntu

**Steps to replicate problem:**
- run docker-compose version 
- add channel
- when channel is online, or "Force record" button is pressed, crash will happen

So maybe solution is to be able uncheck "Set file permissions"? Old version the old version had it turned off by default.

crash wish default settings:

```
2022-05-01 03:41:45.265 | automator <INFO> Stream online for streamer (retry 0)
Notifying clients: streamer is live!: Music
𝕣𝕖𝕝𝕒𝕩𝕚𝕟𝕘 𝕧𝕚𝕕𝕖𝕠𝕘𝕒𝕞𝕖 𝕞𝕦𝕤𝕚𝕔 🌙, category streamOnline
2022-05-01 03:41:45.297 | vodclass <INFO> Create VOD JSON for streamer: streamer_2022-05-01T03_39_18Z_46310632669.json @ /usr/local/share/twitchautomator/data/storage/vods/streamer
2022-05-01 03:41:45.301 | vodclass <SUCCESS> Saving JSON of streamer_2022-05-01T03_39_18Z_46310632669  (create json)
Stopped watching streamer_2022-05-01T03_39_18Z_46310632669
Watching streamer_2022-05-01T03_39_18Z_46310632669
2022-05-01 03:41:45.309 | channel <DEBUG> Fetching channel data for id 95904326, force: false
2022-05-01 03:41:45.310 | channel <DEBUG> Channel data found in memory cache for id 95904326
2022-05-01 03:41:45.311 | channel <DEBUG> Returning memory cache for id 95904326
52.12.79.235 - - [01/May/2022:03:41:45 +0000] "POST /api/v0/hook HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
2022-05-01 03:41:45.315 | channel <DEBUG> Fetching channel data for id 95904326, force: false
2022-05-01 03:41:45.317 | channel <DEBUG> Channel data found in memory cache for id 95904326
2022-05-01 03:41:45.317 | channel <DEBUG> Returning memory cache for id 95904326
2022-05-01 03:41:45.319 | vodclass <ERROR> No chapters on streamer_2022-05-01T03_39_18Z_46310632669!
2022-05-01 03:41:45.320 | vodclass <DEBUG> VOD Class for streamer_2022-05-01T03_39_18Z_46310632669 with api disabled!
Watching streamer_2022-05-01T03_39_18Z_46310632669
streamer_2022-05-01T03_39_18Z_46310632669 is not yet remuxed but no ts file found, skipping!
2022-05-01 03:41:45.322 | vodclass <WARNING> Loaded VOD streamer_2022-05-01T03_39_18Z_46310632669 is not finalized!
2022-05-01 03:41:45.326 | vodclass <DEBUG> Can't request duration because streamer_2022-05-01T03_39_18Z_46310632669 is converting!
WebSocket payload start_download dispatching...
No clients connected to broker for data: {"server":true,"action":"start_download","data":{"vod":{"basenam...
2022-05-01 03:41:45.329 | vodclass <WARNING> Saving JSON of streamer_2022-05-01T03_39_18Z_46310632669 with no chapters!!
2022-05-01 03:41:45.329 | vodclass <SUCCESS> Saving JSON of streamer_2022-05-01T03_39_18Z_46310632669  (is_capturing set)
TypeError [ERR_INVALID_ARG_TYPE]: The "uid" argument must be of type number. Received type string ('nobody')
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at new NodeError (node:internal/errors:372:5)
    at __node_internal_ (node:internal/validators:75:13)
    at Object.chownSync (node:fs:1947:3)
    at _TwitchVOD.setPermissions (/usr/local/share/twitchautomator/server/src/Core/TwitchVOD.ts:1511:20)
    at _TwitchVOD.saveJSON (/usr/local/share/twitchautomator/server/src/Core/TwitchVOD.ts:1479:14)
    at Automator.download (/usr/local/share/twitchautomator/server/src/Core/Automator.ts:596:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Automator.handle (/usr/local/share/twitchautomator/server/src/Core/Automator.ts:190:13) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Node.js v17.9.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by MrBrax** [comment]
It should be off by default, i haven't tried myself, so errors make sense
