### ISSUE TITLE
dashboard mostly blank when streamers channel changes names?

### ISSUE THREAD

**Issue by Intrepd** [MrBrax/TwitchAutomator#52]
Using TwitchAutomator 5.0.5/0.2.1, I wasn't able to view most of my dashboard this morning.  I saw this stack in my log:

```
2021-05-13 10:29:53.307 | helper | <ERROR> Failed to fetch channel id for ExLibrisDJ: {"data":[]}
NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: Typed property App\TwitchChannel::$userid must be string or null, bool used in /var/www/twitchautomator/src/TwitchChannel.php:43

Stack trace:
#0 /var/www/twitchautomator/src/Controller/ApiController.php(67): App\TwitchChannel->load()
#1 /var/www/twitchautomator/src/Traits/ApiChannels.php(49): App\Controller\ApiController->generateStreamerList()
#2 /var/www/twitchautomator/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): App\Controller\ApiController->channels_list()
#3 /var/www/twitchautomator/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#4 /var/www/twitchautomator/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#5 /var/www/twitchautomator/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#6 /var/www/twitchautomator/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#7 /var/www...

```

I went to check on ExLibrisDJ and twitch showed the "Sorry. Unless you’ve got a time machine, that content is unavailable."  I think they changed their name to ExLibrisOfficial, but not 100% sure.

I manually removed ExLibrisDJ from my config.json and things seem to be working again.

Just thought I'd pass this scenario along and not sure how helpful this is.

**Comment by MrBrax** [comment]
yeah i'm gonna have to rewrite this whole thing to use usernames instead of display names one day, unless this was an actual username change
