### ISSUE TITLE
Cannot add Channel

### ISSUE THREAD

**Issue by Serph91P** [MrBrax/TwitchAutomator#83]
After I add a channel I don't get any message. The menu just collapses, but the added channel appears in the Settings Channel Overview.
Log Says `<html><body>

  | helper | FATAL | Subscribe  for 22552479:channel.update (giantwaffle) failed: Client error: `POST  https://api.twitch.tv/helix/eventsub/subscriptions` resulted in a `409  Conflict` response: {"error":"Conflict","status":409,"message":"subscription already  exists"}
-- | -- | -- | --

</body>
</html>`

I did not try to add the channel twice, but the error say already exists? 

Using Docker have set the basic stuff as written in other issues.

**Comment by Serph91P** [comment]
Just saw that in the dashboard it also says disconnected dunno why, everything is running.

**Comment by Serph91P** [comment]
Now the channels appeared in settings, but dashboards is just loading but nothing shows up. Also, one channel is online but is not being recorded. Something is really off.

**Comment by Serph91P** [comment]
<html><body>


2022-01-19 14:55:37.661 | helper | INFO | Fetched channel data online for Giantwaffle
-- | -- | -- | --
2022-01-19 14:55:41.071 | helper | INFO | Fetched channel data online for Giantwaffle
2022-01-19 14:55:56.605 | hook | ERROR | Hook called with invalid JSON.
2022-01-19 14:55:56.631 | config | SUCCESS | Saved config from settings/save
2022-01-19 14:55:58.495 | helper | INFO | Fetched channel data online for Giantwaffle
2022-01-19 14:56:03.100 | helper | INFO | Fetched channel data online for Giantwaffle
2022-01-19 15:03:45.770 | helper | INFO | Fetched channel data online for Giantwaffle
2022-01-19 15:03:57.871 | helper | INFO | Fetched channel data online for Giantwaffle


</body>
</html>

**Comment by MrBrax** [comment]
Considering it constantly checks for channel data online, something must be wrong with your folder permissions.

Was the channel already streaming when you added it?

**Comment by Serph91P** [comment]
Yes was already streaming when I added it. Already tried fixing it like shown here: https://github.com/MrBrax/TwitchAutomator/issues/46#issuecomment-843274253

**Comment by MrBrax** [comment]
The project only starts recording when it recieves the notification from twitch initially, so partway recordings are only forceable, which isn't recommended.

You can check if all subscriptions went through at `/api/v0/subscriptions/list`

The connected/disconnected is the UI responding to live changes via websockets, if that's somehow causing a problem i think you can disable it in the settings.

**Comment by Serph91P** [comment]
This seems to be working, at least it responds with ok and shows subscribed streamer, but it shows the channel multiple times. Is this normal?

**Comment by MrBrax** [comment]
If you can't remove them from the settings, you gotta edit the /config/channels.json file manually

**Comment by Serph91P** [comment]
I meant under the api, there are channels listed that are not in the list anymore, also not in the channels json.

**Comment by MrBrax** [comment]
Internally, channels not in the channels json shouldn't start recording. I should make some kind of subscription browser with unsubbing for each some day.

**Comment by Serph91P** [comment]
Ok deleted those I don't want anymore. But now I cannot add new, after I press add nothing happens, before there was a green message shown that it was added.

**Comment by MrBrax** [comment]
Check the logs, debug mode enabled if needed.

**Comment by Serph91P** [comment]
Just tried another one with debug enabled: `{ "message": "Slim Application Error", "exception": [ { "type": "Exception", "code": 0, "message": "Streamer not found in config: gronkh", "file": "/var/www/twitchautomator/src/TwitchChannel.php", "line": 86 } ] }`
`<html><body>


2022-01-19 16:13:43.879 | SoftwareWrappers.php | DEBUG | Executing  command: /usr/bin/ffmpeg -i  /var/www/twitchautomator/src/../cache/channel/avatar/CohhCarnage.png -y  /var/www/twitchautomator/src/../cache/channel/avatar/CohhCarnage.webp
-- | -- | -- | --
2022-01-19 16:13:43.926 | helper | INFO | Fetched channel data online for CohhCarnage
2022-01-19 16:13:43.934 | helper | DEBUG | Fetched channel data from cache for 26610234 (CohhCarnage)
2022-01-19 16:13:43.937 | job | DEBUG | Channels list empty when getting, load from config.
2022-01-19 16:13:43.945 | helper | DEBUG | Fetched access token from cache


</body>
</html>`

**Comment by MrBrax** [comment]
There's definitely some config mismatch here. No idea how you managed all this haha

Probably easier to remove the channel stuff and start over?

**Comment by Serph91P** [comment]
> There's definitely some config mismatch here. No idea how you managed all this haha
> 
> Probably easier to remove the channel stuff and start over?

you mean like delete the config files or the whole docker setup?

**Comment by MrBrax** [comment]
The channels config first at least, then maybe the main one

**Comment by Serph91P** [comment]
> The channels config first at least, then maybe the main one

Ok deleted first the channel config. When I try to add one: `{ "message": "Slim Application Error", "exception": [ { "type": "Exception", "code": 0, "message": "Streamer not found in config: gronkh", "file": "/var/www/twitchautomator/src/TwitchChannel.php", "line": 86 } ] }`

Log: `<html><body>


2022-01-19 16:24:15.969 | config | SUCCESS | Saved channels config
-- | -- | -- | --
2022-01-19 16:24:15.975 | helper | DEBUG | Fetched access token from cache
2022-01-19 16:24:16.340 | SoftwareWrappers.php | DEBUG | Executing  command: /usr/bin/ffmpeg -i  /var/www/twitchautomator/src/../cache/channel/avatar/GRONKH.png -y  /var/www/twitchautomator/src/../cache/channel/avatar/GRONKH.webp
2022-01-19 16:24:16.398 | helper | INFO | Fetched channel data online for Gronkh
2022-01-19 16:24:16.408 | helper | DEBUG | Fetched channel data from cache for 12875057 (GRONKH)
2022-01-19 16:24:28.527 | helper | DEBUG | Fetched access token from cache
2022-01-19 16:24:28.535 | job | DEBUG | Channels list empty when getting, load from config.
2022-01-19 16:24:28.541 | helper | DEBUG | Fetched access token from cache
2022-01-19 16:24:28.968 | SoftwareWrappers.php | DEBUG | Executing  command: /usr/bin/ffmpeg -i  /var/www/twitchautomator/src/../cache/channel/avatar/GRONKH.png -y  /var/www/twitchautomator/src/../cache/channel/avatar/GRONKH.webp
2022-01-19 16:24:29.022 | helper | INFO | Fetched channel data online for Gronkh
2022-01-19 16:24:29.029 | helper | DEBUG | Fetched channel data from cache for 12875057 (GRONKH)
2022-01-19 16:24:29.069 | helper | DEBUG | Fetched access token from cache
2022-01-19 16:24:29.077 | helper | DEBUG | Fetched access token from cache


</body>
</html>`

After that did not work I deleted the whole folder. There where alot of errors in the log. But still it save the config?
`<html><body>


2022-01-19 16:26:12.766 | config | FATAL | Saving config failed, permissions issue?
-- | -- | -- | --
2022-01-19 16:26:38.767 | hook | ERROR | Hook called with invalid JSON.
2022-01-19 16:26:38.800 | config | SUCCESS | Saved config from settings/save
2022-01-19 16:26:39.814 | helper | INFO | Fetched new access token
2022-01-19 16:26:44.553 | hook | ERROR | Hook called with invalid JSON.
2022-01-19 16:26:44.561 | helper | DEBUG | Fetched access token from cache
2022-01-19 16:26:44.578 | websocket | ERROR | Websocket  send error: Could not open socket to "localhost:8765": Address not  available (99) stream_socket_client(): Unable to connect to  tcp://localhost:8765 (Address not available).
2022-01-19 16:26:44.581 | config | SUCCESS | Saved config from settings/save
2022-01-19 16:26:50.031 | helper | DEBUG | Fetched access token from cache
2022-01-19 16:26:50.043 | hook | ERROR | Hook called with invalid JSON.
2022-01-19 16:26:50.051 | helper | DEBUG | Fetched access token from cache
2022-01-19 16:26:50.070 | websocket | ERROR | Websocket  send error: Could not open socket to "localhost:8765": Address not  available (99) stream_socket_client(): Unable to connect to  tcp://localhost:8765 (Address not available).
2022-01-19 16:26:50.074 | config | SUCCESS | Saved config from settings/save
2022-01-19 16:26:54.148 | helper | DEBUG | Fetched access token from cache
2022-01-19 16:26:54.159 | job | DEBUG | Channels list empty when getting, load from config.
2022-01-19 16:26:54.161 | api | WARNING | No channels in channel list
2022-01-19 16:26:54.193 | helper | DEBUG | Fetched access token from cache
2022-01-19 16:26:54.194 | helper | DEBUG | Fetched access token from cache


</body>
</html>`

I kinda don't get what is happening. BTW stopped and startet the docker in between.

**Comment by MrBrax** [comment]
Seems like your config is still there, you should probably check your whole setup for that.

**Comment by Serph91P** [comment]
OK, deleted the whole docker setup `docker-compose down -v --rmi all --remove-orphans`. and deleted the folder completely. Used a new downloaded docker-compose file. Also new folder was used.
This is the output of the log after fresh start.

`<html><body>


2022-01-19 16:41:45.327 | helper | ERROR | Missing either api secret or client id, aborting fetching of access token!
-- | -- | -- | --
2022-01-19 16:41:45.348 | config | FATAL | Saving config failed, permissions issue?
2022-01-19 16:41:48.607 | helper | ERROR | Missing either api secret or client id, aborting fetching of access token!
2022-01-19 16:41:49.698 | helper | ERROR | Missing either api secret or client id, aborting fetching of access token!
2022-01-19 16:41:49.707 | api | WARNING | No channels in channel list
2022-01-19 16:41:49.737 | helper | ERROR | Missing either api secret or client id, aborting fetching of access token!
2022-01-19 16:41:49.753 | helper | ERROR | Missing either api secret or client id, aborting fetching of access token!
2022-01-19 16:42:02.930 | helper | ERROR | Missing either api secret or client id, aborting fetching of access token!
2022-01-19 16:42:02.940 | hook | ERROR | Hook called with invalid JSON.
2022-01-19 16:42:03.914 | helper | INFO | Fetched new access token
2022-01-19 16:42:03.940 | config | SUCCESS | Saved config from settings/save
2022-01-19 16:42:04.934 | helper | INFO | Fetched new access token
2022-01-19 16:42:06.646 | api | WARNING | No channels in channel list
2022-01-19 16:42:23.891 | helper | INFO | Fetched channel data online for Gronkh
2022-01-19 16:42:23.901 | helper | INFO | Subscribing to 12875057 (gronkh)...
2022-01-19 16:42:23.904 | helper | INFO | Subscribe to 12875057:stream.online (gronkh)
2022-01-19 16:42:24.121 | helper | FATAL | Subscribe  for 12875057:stream.online (gronkh) failed: Client error: `POST  https://api.twitch.tv/helix/eventsub/subscriptions` resulted in a `409  Conflict` response: {"error":"Conflict","status":409,"message":"subscription already  exists"}
2022-01-19 16:42:24.124 | helper | INFO | Requesting subscriptions list
2022-01-19 16:42:24.362 | helper | INFO | Get subscription id from endpoint for 12875057:stream.online
2022-01-19 16:42:24.365 | helper | SUCCESS | Found subscription id from endpoint for 12875057:stream.online : df0cff62-f297-4814-bcd1-51de0d19aeb2
2022-01-19 16:42:24.376 | helper | INFO | Subscribe to 12875057:stream.offline (gronkh)
2022-01-19 16:42:24.605 | helper | FATAL | Subscribe  for 12875057:stream.offline (gronkh) failed: Client error: `POST  https://api.twitch.tv/helix/eventsub/subscriptions` resulted in a `409  Conflict` response: {"error":"Conflict","status":409,"message":"subscription already  exists"}
2022-01-19 16:42:24.608 | helper | INFO | Requesting subscriptions list
2022-01-19 16:42:24.846 | helper | INFO | Get subscription id from endpoint for 12875057:stream.offline
2022-01-19 16:42:24.849 | helper | SUCCESS | Found subscription id from endpoint for 12875057:stream.offline : b9ed9f38-4da6-4b86-9957-d2cbf07b456a
2022-01-19 16:42:24.858 | helper | INFO | Subscribe to 12875057:channel.update (gronkh)
2022-01-19 16:42:25.078 | helper | FATAL | Subscribe  for 12875057:channel.update (gronkh) failed: Client error: `POST  https://api.twitch.tv/helix/eventsub/subscriptions` resulted in a `409  Conflict` response: {"error":"Conflict","status":409,"message":"subscription already  exists"}
2022-01-19 16:42:25.081 | helper | INFO | Requesting subscriptions list
2022-01-19 16:42:25.318 | helper | INFO | Get subscription id from endpoint for 12875057:channel.update
2022-01-19 16:42:25.321 | helper | SUCCESS | Found subscription id from endpoint for 12875057:channel.update : ff900daf-9ac9-49f6-9921-bafc050c59d2
2022-01-19 16:42:25.332 | config | SUCCESS | Saved channels config
2022-01-19 16:42:25.753 | helper | INFO | Fetched channel data online for Gronkh
2022-01-19 16:42:30.307 | helper | INFO | Fetched channel data online for Gronkh


</body>
</html>`

Channel is not added on the website but its available in the channels.json
![grafik](https://user-images.githubusercontent.com/8904984/150175633-8af61957-9544-4f03-b8e2-e211e752ef24.png)
![grafik](https://user-images.githubusercontent.com/8904984/150175683-546cdcc5-09c4-4345-a8d9-1577fdba4380.png)

**Comment by MrBrax** [comment]
are there any console errors in the browser?

**Comment by Serph91P** [comment]
> are there any console errors in the browser?

yes there are: 
`Error: Request failed with status code 500
    exports createError.js:16
    exports settle.js:17
    x xhr.js:66
Dashboard.vue:197:16
    fetchStreamers Dashboard.vue:197`

`No payload for notification sub Dashboard.vue:310:20
    notificationSub Dashboard.vue:310
    commit vuex.cjs.js:446
    commit vuex.cjs.js:446
    commit vuex.cjs.js:378
    created Dashboard.vue:42`

`Streamer list notification check payload was updateJobList, abort. Dashboard.vue:315:20
    notificationSub Dashboard.vue:315
    commit vuex.cjs.js:446
    commit vuex.cjs.js:446
    commit vuex.cjs.js:378
    fetchJobs Dashboard.vue:223`

**Comment by Serph91P** [comment]
> i'm not sure i have any idea at this point, very odd isolated error

Thanks for your help anyway, much appreciated.

**Comment by MrBrax** [comment]
pushed an update that adds a simple subscription viewer/unsubber in the about page, maybe that would help some part of it

**Comment by Serph91P** [comment]
> pushed an update that adds a simple subscription viewer/unsubber in the about page, maybe that would help some part of it

unsubscribed from all only one I cannot unsubscribe:

`<html><body>


2022-01-19 18:00:13.130 | helper | SUCCESS | Unsubscribed from eventsub 642a9f80-5928-4936-a208-f8c0b4ca0435 successfully
-- | -- | -- | --
2022-01-19 18:00:13.180 | helper | INFO | Requesting subscriptions list
2022-01-19 18:00:14.432 | helper | INFO | Unsubscribing from eventsub id 5917e9f0-1151-4ced-97d3-4e55ffdb03c3
2022-01-19 18:00:14.813 | helper | SUCCESS | Unsubscribed from eventsub 5917e9f0-1151-4ced-97d3-4e55ffdb03c3 successfully
2022-01-19 18:00:14.878 | helper | INFO | Requesting subscriptions list
2022-01-19 18:00:15.823 | helper | INFO | Unsubscribing from eventsub id c7af244e-8910-4896-8ac7-1041eb4de9ef
2022-01-19 18:00:16.225 | helper | SUCCESS | Unsubscribed from eventsub c7af244e-8910-4896-8ac7-1041eb4de9ef successfully
2022-01-19 18:00:16.291 | helper | INFO | Requesting subscriptions list
2022-01-19 18:00:17.660 | helper | INFO | Unsubscribing from eventsub id 1079b9a5-bd95-462d-aaba-b10c8d4bd51a
2022-01-19 18:00:18.079 | helper | SUCCESS | Unsubscribed from eventsub 1079b9a5-bd95-462d-aaba-b10c8d4bd51a successfully
2022-01-19 18:00:18.113 | helper | INFO | Requesting subscriptions list
2022-01-19 18:00:20.742 | helper | INFO | Unsubscribing from eventsub id 13fa886e-8066-47ab-982b-46bccbc737bf
2022-01-19 18:00:21.098 | helper | SUCCESS | Unsubscribed from eventsub 13fa886e-8066-47ab-982b-46bccbc737bf successfully
2022-01-19 18:00:21.132 | helper | INFO | Requesting subscriptions list
2022-01-19 18:00:22.372 | helper | INFO | Unsubscribing from eventsub id 3b2c8f11-ce28-47f5-81b9-d9f49d7436fd
2022-01-19 18:00:22.970 | helper | SUCCESS | Unsubscribed from eventsub 3b2c8f11-ce28-47f5-81b9-d9f49d7436fd successfully
2022-01-19 18:00:23.003 | helper | INFO | Requesting subscriptions list
2022-01-19 18:00:24.880 | helper | INFO | Unsubscribing from eventsub id a508caa0-95ec-4c85-adf6-d9e5b24952f5
2022-01-19 18:00:25.204 | helper | SUCCESS | Unsubscribed from eventsub a508caa0-95ec-4c85-adf6-d9e5b24952f5 successfully
2022-01-19 18:00:25.239 | helper | INFO | Requesting subscriptions list
2022-01-19 18:00:30.182 | helper | INFO | Unsubscribing from eventsub id 8dcaa821-53c7-4653-8ddc-ac1ae7238f9d
2022-01-19 18:00:30.489 | helper | SUCCESS | Unsubscribed from eventsub 8dcaa821-53c7-4653-8ddc-ac1ae7238f9d successfully
2022-01-19 18:00:30.525 | helper | INFO | Requesting subscriptions list
2022-01-19 18:00:31.791 | helper | INFO | Unsubscribing from eventsub id 4192506d-e02e-482f-8bf8-a72c7e6397ce
2022-01-19 18:00:32.099 | helper | SUCCESS | Unsubscribed from eventsub 4192506d-e02e-482f-8bf8-a72c7e6397ce successfully
2022-01-19 18:00:32.135 | helper | INFO | Requesting subscriptions list
2022-01-19 18:00:33.271 | helper | INFO | Unsubscribing from eventsub id ff900daf-9ac9-49f6-9921-bafc050c59d2
2022-01-19 18:00:33.575 | helper | SUCCESS | Unsubscribed from eventsub ff900daf-9ac9-49f6-9921-bafc050c59d2 successfully
2022-01-19 18:00:33.607 | helper | INFO | Requesting subscriptions list
2022-01-19 18:00:34.647 | helper | INFO | Unsubscribing from eventsub id b9ed9f38-4da6-4b86-9957-d2cbf07b456a
2022-01-19 18:00:34.947 | helper | SUCCESS | Unsubscribed from eventsub b9ed9f38-4da6-4b86-9957-d2cbf07b456a successfully
2022-01-19 18:00:34.984 | helper | INFO | Requesting subscriptions list
2022-01-19 18:00:36.008 | helper | INFO | Unsubscribing from eventsub id df0cff62-f297-4814-bcd1-51de0d19aeb2
2022-01-19 18:00:36.307 | helper | SUCCESS | Unsubscribed from eventsub df0cff62-f297-4814-bcd1-51de0d19aeb2 successfully
2022-01-19 18:00:36.342 | helper | INFO | Requesting subscriptions list
2022-01-19 18:00:41.271 | helper | INFO | Unsubscribing from eventsub id df0cff62-f297-4814-bcd1-51de0d19aeb2
2022-01-19 18:00:41.539 | helper | FATAL | Unsubscribe  from eventsub df0cff62-f297-4814-bcd1-51de0d19aeb2 error: Client error:  `DELETE  https://api.twitch.tv/helix/eventsub/subscriptions?id=df0cff62-f297-4814-bcd1-51de0d19aeb2`  resulted in a `404 Not Found` response: {"error":"Not Found","status":404,"message":"not found"}


</body>
</html>`

**Comment by MrBrax** [comment]
seems like it just didn't update, the previous one was the same

**Comment by Serph91P** [comment]
ok, startet adding a new streamer, this appeared instant in the overview. Even when the successful message did not appear.
![grafik](https://user-images.githubusercontent.com/8904984/150188442-2337000c-efc2-49ab-984e-f1588f953e71.png)
But the dashboard remains empty/loading.
![grafik](https://user-images.githubusercontent.com/8904984/150188501-7f380529-b531-44e1-96e0-d79a3b00d28d.png)

**Comment by MrBrax** [comment]
are there any errors in the php/webserver logs?

**Comment by MrBrax** [comment]
or maybe, if you check the network requests with the dev console when loading, what does the api for the channels return?

**Comment by Serph91P** [comment]
> or maybe, if you check the network requests with the dev console when loading, what does the api for the channels return?

![grafik](https://user-images.githubusercontent.com/8904984/150189167-acce1178-8b49-49ff-88d9-cdd69dec1a77.png)
![grafik](https://user-images.githubusercontent.com/8904984/150189457-4d2e8404-549b-4540-bbca-20f10b172409.png)

**Comment by MrBrax** [comment]
yeah i meant the response of it :)

**Comment by Serph91P** [comment]
> yeah i meant the response of it :)

there is no response or Iam to stupid to see :D

**Comment by MrBrax** [comment]
the response tab is empty? then it's probably in the webserver logs

**Comment by Serph91P** [comment]
> the response tab is empty? then it's probably in the webserver logs

![grafik](https://user-images.githubusercontent.com/8904984/150190614-e1fe3975-5de0-49c5-8a25-c225ec8017be.png)
this looks empty

**Comment by MrBrax** [comment]
could be that the docker thing has php errors turned off for rendering then

**Comment by Serph91P** [comment]
> are there any errors in the php/webserver logs?

`2022-01-19 18:22:06.281 | helper | <INFO> Fetched channel data online for Gronkh

NOTICE: PHP message: PHP Fatal error:  Uncaught Exception: Streamer not found in config: gronkh in /var/www/twitchautomator/src/TwitchChannel.php:85

Stack trace:

#0 /var/www/twitchautomator/src/TwitchChannel.php(138): App\TwitchChannel::loadAbstract()

#1 /var/www/twitchautomator/src/TwitchConfig.php(286): App\TwitchChannel::loadFromLogin()

#2 /var/www/twitchautomator/src/TwitchConfig.php(301): App\TwitchConfig::loadChannels()

#3 /var/www/twitchautomator/src/Controller/ApiController.php(68): App\TwitchConfig::getChannels()

#4 /var/www/twitchautomator/src/Traits/ApiChannels.php(49): App\Controller\ApiController->generateStreamerList()

#5 /var/www/twitchautomator/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): App\Controller\ApiController->channels_list()

#6 /var/www/twitchautomator/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()

#7 /var/www/twitchautomator/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()

#8...

2022/01/19 18:22:06 [error] 9#9: *507 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Streamer not found in config: gronkh in /var/www/twitchautomator/src/TwitchChannel.php:85

Stack trace:

#0 /var/www/twitchautomator/src/TwitchChannel.php(138): App\TwitchChannel::loadAbstract()

#1 /var/www/twitchautomator/src/TwitchConfig.php(286): App\TwitchChannel::loadFromLogin()

#2 /var/www/twitchautomator/src/TwitchConfig.php(301): App\TwitchConfig::loadChannels()

#3 /var/www/twitchautomator/src/Controller/ApiController.php(68): App\TwitchConfig::getChannels()

#4 /var/www/twitchautomator/src/Traits/ApiChannels.php(49): App\Controller\ApiController->generateStreamerList()

#5 /var/www/twitchautomator/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): App\Controller\ApiController->channels_list()

#6 /var/www/twitchautomator/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()

#7 /var/www/twitchautomator/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()

#8" while reading response header from upstream, client: 192.168.16.1, server: _, request: "GET /api/v0/channels/list HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host:`

this is alot but there is the error I think

**Comment by MrBrax** [comment]
could it be that the username has an uppercase letter in the config?

**Comment by Serph91P** [comment]
> could it be that the username has an uppercase letter in the config?

OMG that was it. Now I am embarrassed.

**Comment by MrBrax** [comment]
i'll add a check for it when adding channels, somehow twitch accepts case insensitive strings then

**Comment by Serph91P** [comment]
> i'll add a check for it when adding channels, somehow twitch accepts case insensitive strings then

Can I somehow buy you a beer or smth. Thanks again for that support.

**Comment by MrBrax** [comment]
haha well i don't really have anything like that, a bit too humble

unraid? do they use some other kind of system like that, like freenas jails? i guess you could just download it and run it manually

**Comment by Serph91P** [comment]
> haha well i don't really have anything like that, a bit too humble
> 
> unraid? do they use some other kind of system like that, like freenas jails? i guess you could just download it and run it manually

they use docker, but not docker compose only a hacky way available to get docker-compose. I think they use xml (https://wiki.unraid.net/DockerTemplateSchema). Tried to match your docker-compose.yml but did not work. Also tried the hacky docker compse but could not get it to run, too many errors.
I

**Comment by MrBrax** [comment]
oh okay, well if you do figure it out you can make a pull request and i'll add it in

i use freenas myself so can't really help there

**Comment by Serph91P** [comment]
> oh okay, well if you do figure it out you can make a pull request and i'll add it in
> 
> i use freenas myself so can't really help there

The only problem I have is, that you have "3" docker, so I would need 3 xml files for them. I think :D

**Comment by condor125** [comment]
> 

The check you added in commit 0ef28b4e1aecdafadae6d15b86a3ba1016f71166 makes you enter the display name and you have uppercase characters in the config again

**Comment by MrBrax** [comment]
that's very odd considering it doesn't get changed

**Comment by MrBrax** [comment]
have you updated since? i don't have that issue

**Comment by MrBrax** [comment]
if you're running on develop branch the numbers don't really match up, depends more on the latest commit

**Comment by MrBrax** [comment]
alright, then i probably fixed it in develop, should hopefully be stable enough to push to master soon
